### ISSUE TITLE
CSS issue with advanced search layout

### ISSUE THREAD

**Issue by CSSSchaffer** [omeka-s-themes/freedom#4] opened 2023-09-23 13:44 UTC
Advanced item search page displays the "reset" and "search" buttons overlapping the bottom sort boxes
<img width="984" alt="Screenshot 2023-09-23 at 9 40 04 AM" src="https://github.com/omeka-s-themes/freedom/assets/120601506/94d46fcf-9adb-455d-b948-8e51731bf3c1">
<img width="236" alt="Screenshot 2023-09-23 at 9 40 12 AM" src="https://github.com/omeka-s-themes/freedom/assets/120601506/f6e00402-3910-4ff2-a0cf-5a861cbcb051">
. This is due to the rule #advanced-search .advanced-search-content having a margin-bottom attribute of -105px.

**Comment by nelsonamaya82** [comment] 2023-10-09 22:02
Hi @CSSSchaffer,

I tested the case you reported and couldn't reproduce this issue, as the "reset" and "search" buttons behave differently on smaller resolutions than 1024px:

![image](https://github.com/omeka-s-themes/freedom/assets/6953921/fc04d24c-0519-48a3-9928-aefaa206f04b)

Could you please send us further details on the browser, device and resolution you're seeing this issue?

Thanks.

**Comment by CSSSchaffer** [comment] 2023-10-10 15:10
I appreciate you looking into this. I am now trying to recreate the issue myself, and I cannot. I apologize, but I think that perhaps I had unknowingly had a custom style overriding the theme's default rule which resulted in the first screen shot. I see that when the resolution is 1024+, the search / reset floats to the right instead of below. Is that correct? Thanks

**Comment by nelsonamaya82** [comment] 2023-11-15 02:27
@CSSSchaffer I'm glad it's working fine now for you. Yes, on resolutions equal or greater than 1024px, the search / reset buttons float to the right instead of below, and should never overlap the form.

Closing this issue but feel free to open a new one in case you find anything else.

**Closed by nelsonamaya82** 2023-11-15 02:27 UTC
